# Generated by Django 2.1.1 on 2018-09-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='total_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
