# Generated by Django 2.1.1 on 2018-09-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0004_auto_20180901_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
    ]
