# Generated by Django 2.1.1 on 2018-09-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0005_remove_question_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
