# Generated by Django 2.1.1 on 2018-09-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0008_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='upvotes',
            new_name='answer_upvotes',
        ),
        migrations.AddField(
            model_name='upvotes',
            name='upvoted_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quora.Answers'),
        ),
        migrations.AddField(
            model_name='upvotes',
            name='upvoted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quora.User'),
        ),
    ]
