# Generated by Django 2.1.1 on 2018-09-03 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0009_auto_20180902_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotes',
            name='vote_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
