# Generated by Django 2.1.1 on 2018-09-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0010_upvotes_vote_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvotes',
            name='vote_date',
            field=models.DateTimeField(),
        ),
    ]
